language: ruby

rvm:
  - 2.5.0

sudo: false

services:
  - postgresql

before_script:
  - psql -c 'create database natty_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rails db:migrate 
  - bundle exec rspec spec
