language: ruby

rvm:
  - 2.3.0

sudo: false

env:
  - USE_OFFICIAL_GEM_SOURCE=1

services:
  - mongodb

before_script:
  - mongo rtiss_test --eval 'db.addUser("travis", "test");'

script:
  - RAILS_ENV=test bundle exec rspec spec
